# 基础配置
title: "XIAMEN CIF STONE CO.,LTD"
description: "网站描述"
url: "https://lizhijiao110.github.io" 

# 主题配置
agency:
  email: "RYANZHENG@GMAIL.COM"
  phone: "+86 15559195196"
  social:
    - { name: twitter, url: "#" }
    - { name: github, url: "#" }
