# 基础配置
title: "你的公司名称"
description: "网站描述"
url: "https://lizhijiao110.github.io" 

# 主题配置
agency:
  email: "your@email.com"
  phone: "+86 123-4567-8910"
  social:
    - { name: twitter, url: "#" }
    - { name: github, url: "#" }
